---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7.1
  driver_config:
    box: opscode-debian-7.1
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: common
  run_list:
  - recipe[minitest-handler]
  - recipe[pxe_dust_test::common]

- name: server
  run_list:
  - recipe[minitest-handler]
  - recipe[pxe_dust_test::server]

- name: installers
  run_list:
  - recipe[minitest-handler]
  - recipe[pxe_dust_test::installers]

- name: bootstrap_template
  run_list:
  - recipe[minitest-handler]
  - recipe[pxe_dust_test::bootstrap_template]

