---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-14.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: common
  run_list:
  - recipe[minitest-handler]
  - recipe[pxe_dust_test::common]

- name: server
  run_list:
  - recipe[minitest-handler]
  - recipe[pxe_dust_test::server]
  data_bags_path: "examples/"
  attributes:
    pxe_dust:
      default:
        domain: "testing.pxe"

- name: installers
  run_list:
  - recipe[minitest-handler]
  - recipe[pxe_dust_test::installers]

- name: bootstrap_template
  run_list:
  - recipe[minitest-handler]
  - recipe[pxe_dust_test::bootstrap_template]
